name: docker (runtime)

on:
  push:
    branches:
    tags:
    paths:
      - runtime/**
      - .github/workflows/docker-runtime.yml
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: write
    steps:
      -
        name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          images: |
            name=ghcr.io/${{github.repository_owner}}/northstar-runtime
          flavor: |
            latest=false
          tags: |
            type=ref,event=tag
            type=ref,event=branch,enable=${{github.ref != 'refs/heads/master'}}
            type=raw,value=latest,enable=${{github.ref == 'refs/heads/master'}}
          labels: |
            org.opencontainers.image.title=northstar-runtime
            org.opencontainers.image.description=Northstar dedicated server runtime
          annotations: |
            org.opencontainers.image.title=northstar-runtime
            org.opencontainers.image.description=Northstar dedicated server runtime
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64
          context: '{{defaultContext}}:runtime'
          tags: ${{steps.meta.outputs.tags}}
          annotations: ${{steps.meta.outputs.annotations}}
          labels: ${{steps.meta.outputs.labels}}
